# Format the combined Monte-Carlo summary CSV into a LaTeX table float.
#
# Run:  julia --project=Julia Julia/mc_replication/format_mc_table.jl [in.csv] [out.tex]
#   defaults: newest results/mc_combined_summary_<n_rep>.csv -> ../../mc_summary_table.tex
#   (repo root), so supplementary.tex can \input{mc_summary_table.tex}.
#
# Also callable as format_mc_table(incsv, outtex) — run_all.jl uses this after a
# full run so the two steps chain.

using CSV
using DataFrames
using Printf

const FMT_HERE = @__DIR__
const RESULTS_DIR = joinpath(FMT_HERE, "results")
const DEFAULT_OUTTEX = joinpath(FMT_HERE, "..", "..", "mc_summary_table.tex")

# Newest mc_combined_summary_<n_rep>.csv in results/ (run_all.jl bakes n_rep into the name).
function latest_summary_csv(dir::AbstractString = RESULTS_DIR)
    cands = filter(f -> startswith(f, "mc_combined_summary_") && endswith(f, ".csv"),
                   readdir(dir))
    isempty(cands) && error("no mc_combined_summary_*.csv in $dir — run run_all.jl first")
    paths = joinpath.(dir, cands)
    return paths[argmax(mtime.(paths))]
end

# Presentation order and human labels (Results order).
const SCEN_ORDER = ["imputation", "informative_missingness", "recall_bias",
                    "uncertain_dates", "symptom_definition", "date_heaping",
                    "reporting_scheme_change"]
const SCEN_LABEL = Dict(
    "imputation"              => "Imputation (50\\% MCAR)",
    "informative_missingness" => "Informative missingness",
    "recall_bias"             => "Recall bias",
    "uncertain_dates"         => "Uncertain dates",
    "symptom_definition"      => "Symptom definitions",
    "date_heaping"            => "Date heaping",
    "reporting_scheme_change" => "Reporting-scheme change",
)

esc(s) = replace(String(s), "_" => "\\_")

function cell(sub, method, metric)
    r = sub[(sub.method .== method) .& (sub.metric .== metric), :]
    nrow(r) == 1 || error("expected 1 row for $method/$metric, got $(nrow(r))")
    return r[1, :]
end

# "x.xx [lo--hi]" — brackets for the range, so header units in (days) don't clash.
val(row) = @sprintf("\$%.2f\$ {\\scriptsize[\$%.2f\$--\$%.2f\$]}", row.mean_est, row.est_lo, row.est_hi)
# "p.p [lo, hi]" for percent bias; reference rows (bias exactly 0 with a
# zero-width interval) collapse to a dash rather than a self-referential 0.0.
pct(row) = (row.mean_pct == 0 && row.pct_lo == 0 && row.pct_hi == 0) ? "--" :
    @sprintf("\$%.1f\$ {\\scriptsize[\$%.1f\$, \$%.1f\$]}", row.mean_pct, row.pct_lo, row.pct_hi)

function format_mc_table(incsv::AbstractString = latest_summary_csv(),
                         outtex::AbstractString = DEFAULT_OUTTEX)
    df = CSV.read(incsv, DataFrame)
    n_rep = df.n_reps[1]

    io = IOBuffer()
    println(io, "% Auto-generated by Julia/mc_replication/format_mc_table.jl — do not edit by hand.")
    println(io, "\\begin{table}[ht]")
    println(io, "\\centering\\footnotesize")
    println(io, "\\caption{Monte-Carlo replication of the DDSA data-quality scenarios ",
                "($(n_rep) simulated line lists per scenario). Each estimate is the mean over ",
                "replications with a 2.5--97.5\\% Monte-Carlo interval in square brackets. The ",
                "final column is the percent bias of the median relative to the matched clean, ",
                "no-degradation, or reference fit from the same replication. Reference rows have ",
                "zero bias by construction, marked with a dash, and serve as a within-scenario check.}")
    println(io, "\\label{tab:mc-replication}")
    println(io, "\\setlength{\\tabcolsep}{4pt}")   # trim padding before scaling
    println(io, "\\resizebox{\\textwidth}{!}{%")    # scale to text width (graphicx)
    println(io, "\\begin{tabular}{llcccc}")
    println(io, "\\toprule")
    println(io, "Scenario & Handling & Median (days) & Mean (days) & SD (days) & Median \\%bias \\\\")
    println(io, "\\midrule")

    for (si, sc) in enumerate(SCEN_ORDER)
        sub = df[df.scenario .== sc, :]
        isempty(sub) && continue
        methods = unique(sub.method)
        # Reference row first (bias exactly 0, zero-width interval), then the rest
        # by |median %bias| ascending. Pinning the reference avoids a near-zero
        # method (rounded -0.0) tying it and slipping ahead under a stable sort.
        isref(m) = (r = cell(sub, m, "median"); r.mean_pct == 0 && r.pct_lo == 0 && r.pct_hi == 0)
        refs = filter(isref, methods)
        rest = sort(filter(!isref, methods); by = m -> abs(cell(sub, m, "median").mean_pct))
        order = vcat(refs, rest)
        first = true
        for m in order
            med = cell(sub, m, "median"); mn = cell(sub, m, "mean"); sd = cell(sub, m, "sd")
            scell = first ? SCEN_LABEL[sc] : ""
            println(io, "$scell & $(esc(m)) & $(val(med)) & $(val(mn)) & $(val(sd)) & $(pct(med)) \\\\")
            first = false
        end
        si < length(SCEN_ORDER) && println(io, "\\midrule")
    end

    println(io, "\\bottomrule")
    println(io, "\\end{tabular}%")
    println(io, "}")   # close \resizebox
    println(io, "\\end{table}")

    write(outtex, String(take!(io)))
    println("Wrote $outtex  (n_rep = $n_rep replications)")
    return outtex
end

# Only runs when invoked directly, not when included by run_all.jl.
if abspath(PROGRAM_FILE) == @__FILE__
    incsv  = length(ARGS) >= 1 ? ARGS[1] : latest_summary_csv()
    outtex = length(ARGS) >= 2 ? ARGS[2] : DEFAULT_OUTTEX
    format_mc_table(incsv, outtex)
end
